spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/prosn?serverTimezone=UTC&characterEncoding=UTF-8
    username: prosn
    password: prosn705@#
  mvc:
    path match:
      matching-strategy: ant_path_matcher


  mail:
    host: smtp.naver.com
    port: 465
    username: prosnteam
    password: prosn705@#
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true


  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true;
        use_sql_comments: true

logging.level:
  org.hibernate.SQL: debug

server.error.include-message: always
jwt:
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK